#include "gl_load.h"

PFNGLACTIVETEXTUREPROC           glActiveTexture;
PFNGLATTACHSHADERPROC            glAttachShader;
PFNGLBINDBUFFERPROC              glBindBuffer;
PFNGLBINDTEXTUREPROC             glBindTexture;
PFNGLBINDVERTEXARRAYPROC         glBindVertexArray;
PFNGLBUFFERDATAPROC              glBufferData;
PFNGLCLEARCOLORPROC              glClearColor;
PFNGLCLEARPROC                   glClear;
PFNGLCOMPILESHADERPROC           glCompileShader;
PFNGLCREATEPROGRAMPROC           glCreateProgram;
PFNGLCREATESHADERPROC            glCreateShader;
PFNGLCULLFACEPROC                glCullFace;
PFNGLDELETEBUFFERSPROC           glDeleteBuffers;
PFNGLDELETESHADERPROC            glDeleteShader;
PFNGLDELETETEXTURESPROC          glDeleteTextures;
PFNGLDELETEVERTEXARRAYSPROC      glDeleteVertexArrays;
PFNGLDRAWELEMENTSPROC            glDrawElements;
PFNGLENABLEPROC                  glEnable;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLFRONTFACEPROC               glFrontFace;
PFNGLGENBUFFERSPROC              glGenBuffers;
PFNGLGENERATEMIPMAPPROC          glGenerateMipmap;
PFNGLGENTEXTURESPROC             glGenTextures;
PFNGLGENVERTEXARRAYSPROC         glGenVertexArrays;
PFNGLGETPROGRAMINFOLOGPROC       glGetProgramInfoLog;
PFNGLGETPROGRAMIVPROC            glGetProgramiv;
PFNGLGETSHADERINFOLOGPROC        glGetShaderInfoLog;
PFNGLGETSHADERIVPROC             glGetShaderiv;
PFNGLGETUNIFORMLOCATIONPROC      glGetUniformLocation;
PFNGLLINKPROGRAMPROC             glLinkProgram;
PFNGLPOLYGONMODEPROC             glPolygonMode;
PFNGLSHADERSOURCEPROC            glShaderSource;
PFNGLTEXIMAGE2DPROC              glTexImage2D;
PFNGLTEXPARAMETERIPROC           glTexParameteri;
PFNGLTEXPARAMETERIVPROC          glTexParameteriv;
PFNGLUNIFORM1FPROC               glUniform1f;
PFNGLUNIFORM3FPROC               glUniform3f;
PFNGLUNIFORMMATRIX4FVPROC        glUniformMatrix4fv;
PFNGLUSEPROGRAMPROC              glUseProgram;
PFNGLVALIDATEPROGRAMPROC         glValidateProgram;
PFNGLVERTEXATTRIBPOINTERPROC     glVertexAttribPointer;


int gl_load_all(GL_get_proc_address func)
{
  glActiveTexture           = (PFNGLACTIVETEXTUREPROC) func("glActiveTexture");
  glAttachShader            = (PFNGLATTACHSHADERPROC) func("glAttachShader");
  glBindBuffer              = (PFNGLBINDBUFFERPROC) func("glBindBuffer");
  glBindTexture             = (PFNGLBINDBUFFERPROC) func("glBindTexture");
  glBindVertexArray         = (PFNGLBINDVERTEXARRAYPROC) func("glBindVertexArray");
  glBufferData              = (PFNGLBUFFERDATAPROC) func("glBufferData");
  glClear                   = (PFNGLCLEARPROC) func("glClear");
  glClearColor              = (PFNGLCLEARCOLORPROC) func("glClearColor");
  glCompileShader           = (PFNGLCOMPILESHADERPROC) func("glCompileShader");
  glCreateProgram           = (PFNGLCREATEPROGRAMPROC) func("glCreateProgram");
  glCreateShader            = (PFNGLCREATESHADERPROC) func("glCreateShader");
  glCullFace                = (PFNGLCULLFACEPROC) func("glCullFace");
  glDeleteBuffers           = (PFNGLDELETEBUFFERSPROC) func("glDeleteBuffers");
  glDeleteShader            = (PFNGLDELETESHADERPROC) func("glDeleteShader");
  glDeleteTextures          = (PFNGLDELETETEXTURESPROC) func("glDeleteTextures");
  glDeleteVertexArrays      = (PFNGLDELETEVERTEXARRAYSPROC) func("glDeleteVertexArrays");
  glDrawElements            = (PFNGLDRAWELEMENTSPROC) func("glDrawElements");
  glEnable                  = (PFNGLENABLEPROC) func("glEnable");
  glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC) func("glEnableVertexAttribArray");
  glFrontFace               = (PFNGLFRONTFACEPROC) func("glFrontFace");
  glGenBuffers              = (PFNGLGENBUFFERSPROC) func("glGenBuffers");
  glGenerateMipmap          = (PFNGLGENERATEMIPMAPPROC) func("glGenerateMipmap");
  glGenTextures             = (PFNGLGENTEXTURESPROC) func("glGenTextures");
  glGenVertexArrays         = (PFNGLGENVERTEXARRAYSPROC) func("glGenVertexArrays");
  glGetProgramInfoLog       = (PFNGLGETPROGRAMINFOLOGPROC) func("glGetProgramInfoLog");
  glGetProgramiv            = (PFNGLGETPROGRAMIVPROC) func("glGetProgramiv");
  glGetShaderInfoLog        = (PFNGLGETSHADERINFOLOGPROC) func("glGetShaderInfoLog");
  glGetShaderiv             = (PFNGLGETSHADERIVPROC) func("glGetShaderiv");
  glGetUniformLocation      = (PFNGLGETUNIFORMLOCATIONPROC) func("glGetUniformLocation");
  glLinkProgram             = (PFNGLLINKPROGRAMPROC) func("glLinkProgram");
  glPolygonMode             = (PFNGLPOLYGONMODEPROC) func("glPolygonMode");
  glShaderSource            = (PFNGLSHADERSOURCEPROC) func("glShaderSource");
  glTexImage2D              = (PFNGLTEXIMAGE2DPROC) func("glTexImage2D");
  glTexParameteri           = (PFNGLTEXPARAMETERIPROC) func("glTexParameteri");
  glTexParameteriv          = (PFNGLTEXPARAMETERIVPROC) func("glTexParameteriv");
  glUniform1f               = (PFNGLUNIFORM1FPROC) func("glUniform1f");
  glUniform3f               = (PFNGLUNIFORM3FPROC) func("glUniform3f");
  glUniformMatrix4fv        = (PFNGLUNIFORMMATRIX4FVPROC) func("glUniformMatrix4fv");
  glUseProgram              = (PFNGLUSEPROGRAMPROC) func("glUseProgram");
  glValidateProgram         = (PFNGLVALIDATEPROGRAMPROC) func("glValidateProgram");
  glVertexAttribPointer     = (PFNGLVERTEXATTRIBPOINTERPROC) func("glVertexAttribPointer");
  
  return(1);
}
